version: '2'
services:
  postgres:
    build: ./docker/postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - ./data/redis:/data
  bot:
    build: .
    command: ./scripts/wait-for-postgres.sh python dog.py --docker
    volumes:
      - .:/opt/dogbot
    depends_on:
      - postgres
      - redis
