---
version: '3.2'
services:
  bot:
    build: .
    volumes:
      - .:/src
    depends_on:
      - postgres
  postgres:
    build: ./db/
    volumes:
      - ./pgdata:/pgdata
    environment:
      - PGDATA=/pgdata
  redis:
    image: 'redis:alpine'
